<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Jin-PC" name="com.code.test.ibnmsConfig.MQListTest" tests="14" failures="0" timestamp="17 Aug 2014 14:54:24 GMT" time="400.217" errors="6">
  <testcase name="deployMQ" time="20.782" classname="com.code.test.ibnmsConfig.MQListTest"/>
  <testcase name="operateMQ" time="29.420" classname="com.code.test.ibnmsConfig.MQListTest"/>
  <testcase name="deployMQ" time="40.300" classname="com.code.test.ibnmsConfig.MQListTest"/>
  <testcase name="operateMQ" time="11.922" classname="com.code.test.ibnmsConfig.MQListTest"/>
  <testcase name="operateMQ" time="36.975" classname="com.code.test.ibnmsConfig.MQListTest"/>
  <testcase name="deployMQ" time="17.885" classname="com.code.test.ibnmsConfig.MQListTest">
    <error type="java.lang.AssertionError" message="{用例描述=启动可用MQ, 列表匹配数据=seleniumMQ, 操作类型=启动, 列表选择器=MQ名称, 期望值=运行中, 结束标记=结束, 用例编号=CASE6, 是否运行=是, 备注=, 状态字段=运行状态} expected [运行中] but found [已停止]">
      <![CDATA[java.lang.AssertionError: {用例描述=启动可用MQ, 列表匹配数据=seleniumMQ, 操作类型=启动, 列表选择器=MQ名称, 期望值=运行中, 结束标记=结束, 用例编号=CASE6, 是否运行=是, 备注=, 状态字段=运行状态} expected [运行中] but found [已停止]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at com.code.common.Tools.assertEquals(Unknown Source)
	at com.code.test.ibnmsConfig.MQListTest.deployMQ(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
    </error>
  </testcase> <!-- deployMQ -->
  <testcase name="deployMQ" time="17.713" classname="com.code.test.ibnmsConfig.MQListTest">
    <error type="java.lang.AssertionError" message="{用例描述=启动可用MQ, 列表匹配数据=seleniumMQ, 操作类型=启动, 列表选择器=MQ名称, 期望值=运行中, 结束标记=结束, 用例编号=CASE6, 是否运行=是, 备注=, 状态字段=运行状态} expected [运行中] but found [已停止]">
      <![CDATA[java.lang.AssertionError: {用例描述=启动可用MQ, 列表匹配数据=seleniumMQ, 操作类型=启动, 列表选择器=MQ名称, 期望值=运行中, 结束标记=结束, 用例编号=CASE6, 是否运行=是, 备注=, 状态字段=运行状态} expected [运行中] but found [已停止]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at com.code.common.Tools.assertEquals(Unknown Source)
	at com.code.test.ibnmsConfig.MQListTest.deployMQ(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
    </error>
  </testcase> <!-- deployMQ -->
  <testcase name="deployMQ" time="35.250" classname="com.code.test.ibnmsConfig.MQListTest">
    <error type="java.lang.AssertionError" message="{用例描述=启动MQ, 列表匹配数据=seleniumIBMMQ1, 操作类型=启动, 列表选择器=MQ名称, 期望值=运行中, 结束标记=结束, 用例编号=CASE2, 是否运行=是, 备注=, 状态字段=运行状态} expected [运行中] but found [已停止]">
      <![CDATA[java.lang.AssertionError: {用例描述=启动MQ, 列表匹配数据=seleniumIBMMQ1, 操作类型=启动, 列表选择器=MQ名称, 期望值=运行中, 结束标记=结束, 用例编号=CASE2, 是否运行=是, 备注=, 状态字段=运行状态} expected [运行中] but found [已停止]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at com.code.common.Tools.assertEquals(Unknown Source)
	at com.code.test.ibnmsConfig.MQListTest.deployMQ(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
    </error>
  </testcase> <!-- deployMQ -->
  <testcase name="operateMQ" time="38.173" classname="com.code.test.ibnmsConfig.MQListTest"/>
  <testcase name="deployMQ" time="40.449" classname="com.code.test.ibnmsConfig.MQListTest"/>
  <testcase name="deployMQ" time="26.640" classname="com.code.test.ibnmsConfig.MQListTest">
    <error type="java.lang.AssertionError" message="{用例描述=部署可用MQ, 列表匹配数据=seleniumMQ, 操作类型=部署, 列表选择器=MQ名称, 期望值=已部署, 结束标记=结束, 用例编号=CASE5, 是否运行=是, 备注=, 状态字段=部署状态} expected [已部署] but found [未部署]">
      <![CDATA[java.lang.AssertionError: {用例描述=部署可用MQ, 列表匹配数据=seleniumMQ, 操作类型=部署, 列表选择器=MQ名称, 期望值=已部署, 结束标记=结束, 用例编号=CASE5, 是否运行=是, 备注=, 状态字段=部署状态} expected [已部署] but found [未部署]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at com.code.common.Tools.assertEquals(Unknown Source)
	at com.code.test.ibnmsConfig.MQListTest.deployMQ(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
    </error>
  </testcase> <!-- deployMQ -->
  <testcase name="deployMQ" time="26.506" classname="com.code.test.ibnmsConfig.MQListTest">
    <error type="java.lang.AssertionError" message="{用例描述=部署可用MQ, 列表匹配数据=seleniumMQ, 操作类型=部署, 列表选择器=MQ名称, 期望值=已部署, 结束标记=结束, 用例编号=CASE5, 是否运行=是, 备注=, 状态字段=部署状态} expected [已部署] but found [未部署]">
      <![CDATA[java.lang.AssertionError: {用例描述=部署可用MQ, 列表匹配数据=seleniumMQ, 操作类型=部署, 列表选择器=MQ名称, 期望值=已部署, 结束标记=结束, 用例编号=CASE5, 是否运行=是, 备注=, 状态字段=部署状态} expected [已部署] but found [未部署]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at com.code.common.Tools.assertEquals(Unknown Source)
	at com.code.test.ibnmsConfig.MQListTest.deployMQ(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
    </error>
  </testcase> <!-- deployMQ -->
  <testcase name="deployMQ" time="20.753" classname="com.code.test.ibnmsConfig.MQListTest"/>
  <testcase name="deployMQ" time="37.449" classname="com.code.test.ibnmsConfig.MQListTest">
    <error type="java.lang.AssertionError" message="{用例描述=部署MQ, 列表匹配数据=seleniumIBMMQ1, 操作类型=部署, 列表选择器=MQ名称, 期望值=已部署, 结束标记=结束, 用例编号=CASE1, 是否运行=是, 备注=, 状态字段=部署状态} expected [已部署] but found [未部署]">
      <![CDATA[java.lang.AssertionError: {用例描述=部署MQ, 列表匹配数据=seleniumIBMMQ1, 操作类型=部署, 列表选择器=MQ名称, 期望值=已部署, 结束标记=结束, 用例编号=CASE1, 是否运行=是, 备注=, 状态字段=部署状态} expected [已部署] but found [未部署]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at com.code.common.Tools.assertEquals(Unknown Source)
	at com.code.test.ibnmsConfig.MQListTest.deployMQ(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
    </error>
  </testcase> <!-- deployMQ -->
</testsuite> <!-- com.code.test.ibnmsConfig.MQListTest -->
